version: '3.8'

services:
  arangodb:
    build: ./arangodb
    image: my-arangodb
    environment:
      - ARANGO_NO_AUTH=1
    ports:
      - "8529:8529"
    volumes:
      - ./arangodb/arangoData:/var/lib/arangodb3

